@startuml

title GestorLloguers

class Client{
    - String nif
    - String nom
    - String telefon
    - Vector<Lloguer> lloguers
    + Client(nif, nom, telefon)
    + String getNif()
    + String getNom()
    + String getTelefon()
    + String getLloguers()
    + int getNumLloguers()
    + Vector<Lloguer> getLloguers()
    + void setNif(nif)
    + void setNom(nom)
    + void setTelefon(telefon)
    + void afegeix(Lloguer)
    + void elimina(Lloguer)
    + boolean conte(Lloguer)
    + String informe()
    - double importTotal()
    - int bonificacionsTotals()
    - String composaCapsalera()
    - String composaDetall()
    - String composaPeu()
    + String informeHTML()
    - String composaCapsaleraHTML()
    - String composaDetallHTML()
    - String composaPeuHTML()
}
class Vehicle{
    - Categoria categoria
    - String model
    - String marca
    + Vehicle(model, marca, categoria)
    + String getModel()
    + String getMarca()
    + Categoria getCategoria()
    + String getCategoria()
    + void setModel()
    + void setMarca()
    + void setCategoria()
}
class Lloguer{
    - Date data
    - int dies
    - Vehicle vehicle
    - SimpleDateFormat dateFormat
    - static final int PREU_INICIAL_BASIC = 3;
    - static final int PREU_INICIAL_REGULAR = 4;
    - static final int PREU_INICIAL_LUXE = 6;
    - static final int DIES_PER_DESCOMPTE_BASIC = 3;
    - static final int DIES_PER_DESCOMPTE_REGULAR = 2;
    - static final double DISCOMPTE_BASIC = 1.5;
    - static final double DISCOMPTE_REGULAR = 2.5;
    - static final int INCREMENT_PREU = 30;
    + Lloguer(data, dies, vehicle)
    + Date getData()
    + int getDies()
    + Vehicle getVehicle()
    + void setData(data)
    + void setDies(dies)
    + void setVehicle(vehicle)
    - double getPreuRelatiu()
    + int bonificaionsDeLloguer()
    + double getPreuFinal()
}
class GestorLloguersLite{
    ~ static SimpleDateFormat dateFormat
    ~ static String showInfo()
    + static void main([]String)
}
enum Categoria {
    BASIC
    GENERAL
    LUXE
}

Client -> Lloguer
Lloguer -> Vehicle
Vehicle --> Categoria

@enduml