@startuml

title Exercici 10

GestorLloguesLite -> Client: informe()
Client -> Lloguer: quantitat()
Client -> Lloguer: bonificacionsDeLloguer()
Lloguer -> Vehicle: getCategoria()
Lloguer <- Vehicle: return Categoria
Client <- Lloguer: return quantitat
Client <- Lloguer: return bonificacions
GestorLloguesLite <- Client: return informe
@enduml